name: Publish Python SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "tesseral-sdk-node package version"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fern CLI
        run: npm install -g fern-api

      - name: Release Node SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          fern generate --api backend --group node --version ${{ inputs.version }} --log-level debug
