name: Publish Python SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "tesseral-python package version"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fern CLI
        run: npm install -g fern-api

      - name: Release Python SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          fern generate --api backend --group python --version ${{ inputs.version }} --log-level debug
